Repository opea-project/docs, pull requests merged in 2025-04, with the labels that each got.

#310 Add rfc for Routing Agent
  community/rfcs/25-03-03-GenAIComponents-001-Routing-Agent.md
Labels: A0

#322 Add DocIndexRetriever doc
  tutorial/DocIndexRetriever/DocIndexRetriever_Guide.rst
  tutorial/DocIndexRetriever/deploy/gaudi.md
  tutorial/DocIndexRetriever/deploy/xeon.md
  tutorial/index.rst
Labels: A2

#343 Getting Started Guide: ITAC steps update
  getting-started/README.md
  guide/installation/install_docker.sh
Labels: v1.3

#331 [RFC] Code Agent in CodeTrans
  community/rfcs/25-03-14-GenAIExample-001-CodeTrans-with-Agents.md
Labels: documentation, A0

#345 Update and simplify ChatQnA tutorials
  tutorial/ChatQnA/ChatQnA_Guide.rst
  tutorial/ChatQnA/deploy/aipc.md
  tutorial/ChatQnA/deploy/gaudi.md
  tutorial/ChatQnA/deploy/nvidia.md
  tutorial/ChatQnA/deploy/xeon.md
  tutorial/CodeGen/deploy/xeon.md
Labels: documentation, v1.3

#354 Update and simplify DocSum tutorials
  tutorial/DocSum/DocSum_Guide.rst
  tutorial/DocSum/deploy/gaudi.md
  tutorial/DocSum/deploy/xeon.md
Labels: documentation, v1.3

#353 Update and simplify CodeTrans tutorials
  tutorial/CodeTrans/CodeTrans_Guide.rst
  tutorial/CodeTrans/deploy/gaudi.md
  tutorial/CodeTrans/deploy/xeon.md
Labels: documentation, v1.3

#351 Update and simplify CodeGen tutorials
  tutorial/CodeGen/CodeGen_Guide.rst
  tutorial/CodeGen/deploy/gaudi.md
  tutorial/CodeGen/deploy/xeon.md
Labels: documentation, v1.3

#344 Add v1.3 release notes.
  release_notes/RELEASE.md
  release_notes/v1.3.md
Labels: documentation, v1.3
